(function(){var e=void 0,g=true,h=null,j=false;function k(){return function(){}}function m(a){return function(){return this[a]}}function p(a){return function(){return a}}var q,r=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:da;return s.apply(h,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.la=b.prototype;a.prototype=new c;a.prototype.constructor=a};function fa(){}
function ga(a,b,c){switch(typeof b){case "string":ia(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==h){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var f="",i=0;i<d;i++)c.push(f),ga(a,b[i],c),f=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(i=b[f],typeof i!="function"&&(c.push(d),ia(f,c),c.push(":"),ga(a,i,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var la={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ma=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ia(a,b){b.push('"',a.replace(ma,function(a){if(a in la)return la[a];var b=a.charCodeAt(0),f="\\u";b<16?f+="000":b<256?f+="00":b<4096&&(f+="0");return la[a]=f+b.toString(16)}),'"')};var na={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function oa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function pa(a,b){var c="",d=qa(encodeURIComponent(a));d.splice(b||5,d.length);t(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function qa(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,f=2562383102,i=271733878,l=3285377520,o=[],n,D,G,R,U,ha=Math.ceil((a.length/4+2)/16),ca=[ha],L=0,E;L<ha;L++){ca[L]=[];for(n=0;n<16;n++)ca[L][n]=a.charCodeAt(L*64+n*4)<<24|a.charCodeAt(L*64+n*4+1)<<16|a.charCodeAt(L*64+n*4+2)<<8|a.charCodeAt(L*64+n*4+3)}L=(a.length-1)*8;a=ha-1;ca[a][14]=Math.floor(L/Math.pow(2,32));ca[a][15]=L&4294967295;for(L=0;L<ha;L++){for(E=0;E<16;E++)o[E]=
ca[L][E];for(E=16;E<80;E++)o[E]=(o[E-3]^o[E-8]^o[E-14]^o[E-16])<<1|(o[E-3]^o[E-8]^o[E-14]^o[E-16])>>>31;a=c;n=d;D=f;G=i;R=l;for(E=0;E<80;E++)U=Math.floor(E/20),U=(a<<5|a>>>27)+(U==0?n&D^~n&G:U==1?n^D^G:U==2?n&D^n&G^D&G:n^D^G)+R+b[U]+o[E]&4294967295,R=G,G=D,D=n<<30|n>>>2,n=a,a=U;c=c+a&4294967295;d=d+n&4294967295;f=f+D&4294967295;i=i+G&4294967295;l=l+R&4294967295}return[c,d,f,i,l]}
function ra(a){var b=r.navigator,c=r.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];t(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=r.performance;d=d.concat([b&&b.now?b.now():"",document.title,r.location.href,u(),oa()]);return d.concat(a||[]).join()}function v(a,b,c){var d=Array.prototype.slice,f=d.call(arguments,2);return function(){return a.apply(b,f.concat(d.call(arguments)))}}
function w(a){return typeof a!=="undefined"}function x(a){return a&&a.replace(/^www\./,"")}function sa(){var a=r.location.hostname;return a&&a.replace(/^www[0-9]*\./,"")}var ta=/^((https?\:)?(\/\/))/i;function ua(a){return a&&a.replace(ta,"")}var va=/^((https?\:)?(\/\/))?[^\/]*/;function wa(a){return a.replace(va,"")}var xa=/\#.*/;function ya(a){return a.replace(xa,"")}var Aa=/\?[^\#]*/;function Ba(a){return a.toLowerCase()}var Ca=/\/+((\?|\#).*)?$/;function Da(a){return a.replace(Ca,"$1")}
function Ea(a){return a&&a.replace(Aa,"")}function Fa(a){var b=a.match(/\?(.*)$/ig)?a.match(/\?(.*)$/ig)[0].slice(1).replace(/#(.*)?/ig,"").split("&"):[],c=a.match(/#(.*)$/ig)?a.match(/#(.*)$/ig)[0]:"",a=a.match(/[#|\?](.*)?/ig)?a.slice(0,a.search(/[#|\?](.*)?/ig)):a,b=Ga(b,function(a){return a.search("utm")!==0});b.length>0&&(a+="?"+b.join("&"));return a+c}function Ha(a,b){if(a===b)return 0;var c=h;t([Ba,Da,ua,wa,ya,Ea],function(d,f){a=d(a);b=d(b);if(a===b)return c=f+1,j});return c}
function Ia(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function Ja(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function Ka(a){return typeof a==="number"}function La(a){return typeof a==="string"}function Ma(a){return typeof a==="function"}function Na(a){return Object.prototype.toString.call(a)==="[object Array]"}
function Oa(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function u(){return(new Date).getTime()}function Pa(a){return encodeURIComponent(a)}function Qa(){return r.location.protocol==="http:"?"http:":"https:"}function Ra(a){return!!a&&a.constructor===Object}function Sa(a,b){if(!Ra(a)||!Ra(b))return a===b;var c=0,d=g;t(a,function(a,f){c++;return d=a===b[f]});if(!d)return j;var f=0;t(b,function(){f++});return c===f}
function t(a,b){if(Ra(a)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}function Ta(a,b){var c=[];t(a,function(a,f){var i=b(a,f);c.push(i)});return c}function Ua(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function Va(a){for(var b=[51448,50924,33715,53046,66244,66059,16698],c=j,d=0,f=b.length;d<f;d++)if(Sa(b[d],a)){c=g;break}return c}
function Wa(a){var b=r.pSUPERFLY_video,a=Ua(b,a);if(a>-1)return b[a]}function Ga(a,b){var c=[];t(a,function(a){b(a)&&c.push(a)});return c}function Xa(a){if(a){var b=[];ga(new fa,a,b);a=encodeURIComponent(b.join(""))}else a="";return a}function Ya(a){return a===e?0:u()-a}
function Za(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,f=b.length;d<=f;d++)c[d]=[d];for(var i=0,l=a.length;i<=l;i++)c[0][i]=i;for(var o,n,D,d=1;d<=f;d++)for(i=1;i<=l;i++)o=d-1,n=i-1,D=c[o][n],b.charAt(o)==a.charAt(n)?c[d][i]=D:(n=c[d][n]+1,o=c[o][i]+1,D+=2,c[d][i]=Math.min(n,o,D));return c[b.length][a.length]}function $a(a){return a===e?0:u()-a}function y(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}
function ab(){if(bb!==e)return bb;var a=r.navigator.userAgent;return bb=a.indexOf("AppleWebKit")>0&&a.indexOf("FBIOS")>0}var bb;function cb(){}var db=r.setInterval,eb=r.clearInterval,fb=r.setTimeout,gb=r.clearTimeout;function hb(a,b){return db(a,b)}function ib(a){switch(a){case e:return"undefined";case "":return"empty";default:return a}}function jb(a){switch(a){case "undefined":break;case "empty":return"";default:return a}}
function kb(){for(var a=document.domain,b=a.split("."),c=window.location.protocol==="https:"?"; Secure":"",d=0;d<b.length-1&&document.cookie.indexOf("_cbt=_cbt")==-1;)a=b.slice(-1-++d).join("."),document.cookie="_cbt=_cbt; domain="+a+c;document.cookie="_cbt=; expires=Thu, 01 Jan 1970 00:00:01 GMT; domain="+a+c;return a}var lb=g;function mb(a,b,c){if(c)return a;return b&&b[nb]&&lb&&(c=kb(),b[nb]!==c)?a+"_"+sa().split(".")[0]:a}
function ob(a){if(!Va(a))return"";a="";try{var b=r.googletag.pubads();if(b){var c=b.getSlots(),d={};t(c,function(a){a=a.getAdUnitPath();d[a]?d[a]+=1:d[a]=1});a=Ta(Object.keys(d),function(a){return a+"||"+d[a]}).join(",")}}catch(f){}return encodeURIComponent(a)};function pb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),t(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function qb(a,b){var c="",d=r.location.href.match(/[^?]+[?]([^#]+).*/);if(d){var d=pb(d[1]),f=b||a;d[f]&&(c=d[f])}return encodeURIComponent(c)}function rb(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function sb(a){var b=[];t(tb,function(c){var d=a[c];w(d)&&(Na(d)?t(d,function(a){b.push(c+"="+a)}):Ra(d)?t(d,function(a,c){b.push(c+"="+a)}):((d+"").length||c=="r")&&b.push(c+"="+d))});b.push("_");return b.join("&")}
function ub(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=r.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var f=rb(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||d.href,i=f.indexOf("?");i===-1&&(i=f.indexOf("#"));if(i===-1)i=f.length;i=f.lastIndexOf("/",i);a=i===-1?
"/"+a:f.substr(0,i)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(rb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function vb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function wb(a,b,c,d){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+(a+(d?'="'+d+'"':""))+"]");for(var f=[],b=c.getElementsByTagName(b),c=b.length,i="";c--;)(i=b[c].getAttribute(a))&&(!d||i===d)&&f.push(b[c]);return f}function xb(a,b,c){c=c||"";if(a===e)a=j;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?j:xb(a.parentNode,b,c)}return a}
function yb(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=wb("data-cb-scroll-element"))&&a.length)return a[0][c];if(Ka(r[b]))return r[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function zb(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function Ab(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Bb(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return h;var d=a.ownerDocument.documentElement,f=0,i=w(c)?c+1:-1;La(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&f!==i;){if(c(a))return a;a=a.parentNode;f++}return h}
function Cb(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function Db(a){a=a||window.event;return!a?h:Bb(a.target||a.srcElement,Cb,10)}function Eb(a,b){var c=document.createElement(a);t(b,function(a,b){c.setAttribute(b,a)});return c}function Fb(){return r.document.readyState==="complete"||r.document.readyState!=="loading"&&!r.document.documentElement.doScroll}
function Gb(a){function b(){if(r.document.addEventListener||r.event.type==="load"||r.document.readyState==="complete")r.document.addEventListener?(r.document.removeEventListener("DOMContentLoaded",b,j),r.removeEventListener("load",b,j)):(r.document.detachEvent("onreadystatechange",b),r.detachEvent("onload",b)),a()}Fb()?a():r.document.addEventListener?(r.document.addEventListener("DOMContentLoaded",b,j),r.addEventListener("load",b,j)):(r.document.attachEvent("onreadystatechange",b),r.attachEvent("onload",
b))};function Hb(){this.oa={};this.Ya=1}function Ib(a,b,c,d){a.Ya++;a.oa[b]=a.oa[b]||{};a.oa[b][a.Ya]=[c,d];return a.Ya}function Jb(a,b){if(La(b))a.oa[b]=e,delete a.oa[b];else if(Ka(b)){var c=g;t(a.oa,function(a){t(a,function(f,i){if(parseInt(i,10)===b)return a[i]=e,delete a[i],c=j});return c})}}Hb.prototype.Ja=function(a,b){if(this.oa[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];t(this.oa[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
Hb.prototype.addEventListener=function(a,b){var c=Ib(this,a,b);b._cbEventId=c};Hb.prototype.removeEventListener=function(a,b){this.oa[a]&&this.oa[a][b._cbEventId]&&this.oa[a][b._cbEventId][0]===b&&Jb(this,b._cbEventId)};var z=new Hb;var A={};
A.da=function(){A.Yb?A.Cb("pageload"):(A.kd=[{target:r,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:r,event:"resize"},{target:document.body,event:"mousedown"}],A.Ib=h,A.Va=h,A.Xb={},A.Nc={},t(A.kd,function(a){var b=a.event;Ia(a.target,b,function(a){A.Cb.call(A,b,a)})}),Ib(z,"f",function(){A.Cb("focus")}),A.Cb("pageload"),Ia(document.body,"click",function(a){(a=Db(a))&&z.Ja("c",a)},g),Ia(document.body,"contextmenu",function(a){(a=Db(a))&&z.Ja("r",
a)}),A.Yb=g)};A.pd=function(){var a,b=A.Nc.keydown;if(b===e)return j;b=u()-b;return b<=(a||15E3)&&b>=0};A.zc=100;A.Cb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}A.Ce(a);if(A.Ib===h)A.ad(a);else if(!A.Va||na[A.Va]<na[a])A.Va=a};A.Ce=function(a){A.Nc[a]=u()};A.ad=function(a){A.Ib=fb(A.xd,A.zc);z.Ja("a");A.Xb[a]!==h&&gb(A.Xb[a]);A.ue(a)};
A.ue=function(a){var b=A.Xb;b[a]=fb(function(){gb(b[a]);delete b[a];var c=j;t(b,function(){c=g;return j});c||z.Ja("i")},na[a]+A.zc)};A.xd=function(){gb(A.Ib);A.Ib=h;if(A.Va)A.ad(A.Va),A.Va=h};var Kb,Lb,Mb,Nb,Ob;(function(){var a,b;t(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof r.document[a]==="boolean")return b=c,j});b!==e&&(Nb=a,Ob=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Mb=b+"visibilitychange")})();var Pb=j;function Qb(){Pb=Ob&&r.document[Ob]==="prerender"?g:j}function Rb(){Lb=g;z.Ja("f")}function Sb(){Lb=j;z.Ja("b")}
function Tb(a,b,c){r.addEventListener?r.addEventListener(a,c,j):r.document.attachEvent&&r.document.attachEvent(b,c)}function Ub(){var a=g;!ab()&&r.document.hasFocus&&(a=r.document.hasFocus());var b=j;Nb&&(b=r.document[Nb]);return a&&!b}function Vb(){Ub()?Rb():Sb()}function Wb(a){Qb();if(Pb){var b=j,c=function(){b||(Qb(),Pb||(b=g,a(),r.window.setTimeout(function(){r.document.removeEventListener(Mb,c,j)},100)))};r.document.addEventListener(Mb,c,j)}else a()};function Xb(){this.k=r._sf_async_config||{};this.Ic=v(this.Tc,this)}Xb.prototype.da=function(){this.ib=0};Xb.prototype.Tc=k();Xb.prototype.jb=function(a){if(!Pb){var b=this.Ic,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};Xb.prototype.za=function(){this.Ic=h};var B="path",C="domain",Yb="useCanonical",Zb="useCanonicalDomain",$b="title",ac="virtualReferrer",nb="cookieDomain";function F(a,b,c){a[b]=a[b]||c}function bc(a,b){for(var c=r[a]||[];c.length;)b(c.shift());r[a]={push:b}}function cc(a){t(document.getElementsByTagName("script"),function(b){if(typeof b.src==="string"&&b.src.match(/chartbeat.js/))return b=pb(b.src.split("?")[1]),F(a,"uid",b.uid),F(a,C,b.domain),j})}function dc(a,b){return a[b]?encodeURIComponent(a[b]):""}
function ec(a){var b={};t(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b}function fc(a){if(gc(a))return"";var a=a[nb],b=kb();a&&a!==sa()&&a!==b&&(lb=j,r.console.warn("Invalid cookieDomain (must be set to current domain or root domain), defaulting to root domain."));return a&&lb?a:b}function gc(a){return a&&a.noCookies?g:j};var H={};H.td=function(a,b){try{H.create("_cb_test","1",1,a,b);var c=H.N("_cb_test");H.remove("_cb_test",a,b);return c==="1"}catch(d){return j}};H.N=function(a,b){var c=r._sf_async_config;if(gc(c))return"";var a=mb(a,c,b)+"=",d="";t(document.cookie.split(";"),function(b){for(;b.charAt(0)===" ";)b=b.substring(1,b.length);if(b.indexOf(a)===0)return d=b.substring(a.length,b.length),j});return d};
H.create=function(a,b,c,d,f,i){var l=r._sf_async_config;if(gc(l))return"";a=mb(a,l,i);i=new Date;i.setTime(u()+c*1E3);a=a+"="+b+("; expires="+i.toUTCString())+("; path="+d)+(window.location.protocol==="https:"?"; Secure":"")+(f?"; domain="+f:"");return document.cookie=a};H.remove=function(a,b,c,d){return H.N(a,d)?H.create(a,"",-86400,b,c,d):""};var I={};I.ga=function(a){var b=r._sf_async_config;if(!a&&b&&b.noCookies)return h;if(I.ga.Ob!==e)return I.ga.Ob;var a=u()+"",c,d;try{if((d=r.localStorage).setItem("_cb_ls_test",a),c=d.getItem("_cb_ls_test")===a,d.removeItem("_cb_ls_test"),c)return I.ga.Ob=d}catch(f){}return I.ga.Ob=h};I.N=function(a){var b=I.ga();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&u()>c)?(I.remove(a),""):b.getItem(a)||""};
I.create=function(a,b,c){var d=I.ga();if(d){var f=new Date;f.setTime(u()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",f.getTime())}catch(i){}}};I.remove=function(a){var b=I.ga();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function hc(a,b,c,d){this.Eb=a||"";this.Ka=b||"/";this.Dc=d||{};this.Za=(this.bc=gc(this.Dc))?"":c||kb();this.yd=I.ga()!==h||H.td(this.Ka,this.Za);this.dd=j}q=hc.prototype;q.isSupported=m("yd");function ic(a){var b=a.dd;a.dd=j;return b}q.create=function(a,b,c,d){this.bc||(a=d?a:this.Eb+a,(I.ga()?I:H).create(a,b,c,this.Ka,this.Za),I.ga()&&H.create(a,b,c,this.Ka,this.Za))};
q.update=function(a,b,c,d,f,i,l){a=d?a:this.Eb+a;f=La(f)?f:"::";d=(d=this.N(a,g))?d.split(f):[];if(l&&d.length){var o=l(b),n=Ua(d,function(a){return l(a)===o});n!==-1&&d.splice(n,1)}d.push(b);for(Ka(i)&&d.length>i&&d.splice(0,d.length-i);d.length>1&&d.join(f).length>4E3;)d.shift();this.create(a,d.join(f),c,g)};
q.N=function(a,b){if(this.bc)return"";var a=b?a:this.Eb+a,c=(I.ga()?I:H).N(a);!c&&I.ga()&&(c=H.N(a));if(c){this.remove(a,b,"",g);var d=H.N(a),f=this.Dc[nb]&&lb,i=sa(),f=f&&i!==kb();if(c===d&&!f)return d;(i=a!=="_chartbeat2"||!d?j:+d.split(".")[2]<1647357868E3?g:j)&&H.remove(a,this.Ka,this.Za);if(f){if(d)return i?c:d;d=H.N(a,g);return c!==d?c:""}if(d)return i?c:d}return c};q.remove=function(a,b,c,d){if(c!=="")c=this.Za;a=b?a:this.Eb+a;(I.ga()?I:H).remove(a,this.Ka,c);I.ga()&&H.remove(a,this.Ka,c,d)};var jc={cb_rec:g,fbclid:g,ia_share_url:g,gclid:g,dclid:g,gbraid:g,wbraid:g,gclsrc:g,gdfp_req:g,_gl:g,_ga:g,_hsenc:g,_hsmi:g,msclkid:g,lcid:g,sfmc_id:g,sfmc_sub:g,tblci:g,twclid:g,guccounter:g,guce_referrer:g,"pure360.trackingid":g,dicbo:g,addata:g,zip:g,zipcode:g,regi_id:g,segment_id:g,user_id:g,campaign_id:g,sessionid:g,uuid:g,email:g,token:g,req_token:g,paymentredirectuuid:g,authid:g,auth_id:g,auth:g};var kc=/[A-Za-z0-9-_.'+]+(@|%40)\w+([-.]\w+)*\.\w+([-.]\w+)*/g;function lc(a){var b=h;if(a&&(b=mc(),b=!b?b:J(b.pathname)+nc(b.search)+b.hash))return b;var c=r.location,b=J(c.pathname),a=c.search||"",d=/[?&#]/;if(!a||a.length===1&&d.test(a))return b;a=a.replace(/PHPSESSID=[^&]+/,"");d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));a=nc(a);a=J(a);return b+a}
function oc(a){return a&&(a=mc(),a=!a?a:a.hostname)?a:r.location.hostname}function mc(){var a=pc();return!a?a:ub(a.href)}function pc(){var a=h;t(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return a=b,j});return a}for(var qc={},rc=0;rc<81;rc++)qc["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(rc)]=g;function sc(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return qc[c]?String.fromCharCode(c):"%"+b.toUpperCase()}
function J(a){if(!La(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,sc);a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent);return a=a.replace(kc,"")}function nc(a){var b=a;/[?&#]/.test(a[0])&&(b=a.substring(1));a=b.split("&").filter(function(a){a=a.split("=");return a.length<=1?j:jc[a[0].toLowerCase()]?j:kc.exec(a[1])?j:g});return a.length<1?"":"?"+a.join("&")}function tc(a){if(a){var b=a.split("?");return b.length>1?(a=nc(b[1]))&&a.length?J(b[0]+a):J(b[0]):J(a)}return h};function uc(a,b){var c=vc();return w(b)&&!w(c[a])?b:c[a]}function vc(){w(r._cb_shared)||(r._cb_shared={});return r._cb_shared};var K={md:{IDLE:0,He:1,Ge:2,ld:3},sa:0};K.da=function(){if(!K.Yb)Ib(z,"a",K.Fd,K),Ib(z,"i",K.Id,K),Ib(z,"f",K.Hd,K),Ib(z,"b",K.Gd,K),K.Yb=g};K.G=function(){return K.sa};K.Fd=function(){K.sa===1?K.Fa(3):K.sa===0&&K.Fa(2)};K.Id=function(){K.sa===3?K.Fa(1):K.sa===2&&K.Fa(0)};K.Hd=function(){(K.sa===0||K.sa===2)&&K.Fa(3)};K.Gd=function(){K.sa===3?K.Fa(2):K.sa===1&&K.Fa(0)};K.Fa=function(a){K.sa=a;z.Ja("s",a)};function wc(a,b){this.Wb=a||e;this.fc=b||e;this.bb=this.Xa=0;this.Nd=v(this.Od,this);this.cd=this.Wa=h}q=wc.prototype;q.da=function(){this.bb=this.Xa=0;this.Wa=h;this.cd=Ib(z,"s",this.Mc,this);this.Mc(K.G())};q.Mc=function(a){eb(this.Wa);this.Wa=h;if(a===K.md.ld)this.Wa=db(this.Nd,1E3)};q.Od=function(){if(this.Wb===e||this.Wb())this.Xa++,this.bb++,this.fc&&this.fc()};q.terminate=function(){eb(this.Wa);this.Wa=h;Jb(z,this.cd)};q.za=function(){this.terminate();this.fc=this.Wb=e};function xc(){Xb.call(this);this.Na=[];this.B=new hc(this.ed,this.k.cookiePath||"/",fc(this.k),this.k);this.B.remove("_SUPERFLY_nosample");this.na=new wc;this.ic=v(this.gb,this);Ia(r,"pagehide",this.ic);this.yb=j;yc(v(this.da,this))}ea(xc,Xb);function yc(a){Gb(function(){Wb(a)})}q=xc.prototype;q.rc=g;q.kc=j;
q.da=function(){xc.la.da.call(this);this.wb=this.Qa=0;this.Ua=u();this.Ea=pa(zc(this));this.pc=g;this.zb=72E5;if(this.rc){var a=+this.k.sessionLength;if(!isNaN(a))this.zb=a*6E4}a=uc("d");if(!a){var a=[],b=this.B.N("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>6&&(a=[]);var b=u(),c=this.B.N("_cb",g);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var d=b-+(a[1]||0),f=b-+(a[2]||0);vc().n=c&&d>18E5&&f<2592E6?0:1;var d=a[4],i=parseInt(a[5],10)||0;if(!(f=f>18E5))if(Ac(this))f=j;else{var f=Bc(this),f=decodeURIComponent(f),
f=Cc(f)||f,l;l=Dc(this);l=decodeURIComponent(l);l=Cc(l)||l;f=f!==l}!d||f?(d=pa(zc(this)),a[4]=d,i=1,this.B.remove("_cb_svref",g)):i+=1;a[5]=i;i="1";f=a&&+a[2];d=a&&a[3];if(a&&f&&d)if(i=Math.abs((Oa(b)-Oa(f))/864E5)){i=Math.min(i,16)-1;for(f="";i--;)f+=0;i=(d+f+"1").slice(-16)}else i=d;d=i;c||(c=this.k.utoken||pa(zc(this),3),a[1]=b);a[2]=b;a[3]=d;this.k.utoken=this.lb;this.B.create("_cb",c,34128E3,g);this.B.create("_chartbeat2",a.join("."),34128E3,g);a[0]=c;vc().d=a}this.Oe=a.join(".");var o;c=+a[1];
d=+a[2];if((b=a[3])&&c&&d)o=(Math.min((Math.abs((Oa(d)-Oa(c))/864E5)||0)+1,16,b.length)-1).toString(16),o+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Lc=o;this.ac=uc("n",1);this.lb=a[0];this.ye=a[4];this.we=a[5];this.xe=Dc(this);this.B.create("_cb_svref",Dc(this),1800,g);this.na.da();K.da();A.da();Kb||(Lb=Ub(),Mb&&r.document.addEventListener&&r.document.addEventListener(Mb,Vb,j),Tb("focus","onfocusin",Rb),Tb("blur","onfocusout",Sb),Lb&&Rb(),Kb=g);this.eb=0;this.od=Ib(z,"a",this.Td,this);this.kc=
g;if(this.gc)fb(this.gc,0),this.gc=h};q.ob=function(){if(!this.B.N("_SUPERFLY_lockout"))this.kc?!Fb()&&!this.yb?(this.Db=v(this.tc,this),Ia(r,"load",this.Db)):this.tc():this.gc=v(this.ob,this)};q.tc=function(){this.hb=Ec();A.da();this.vb=hb(v(this.qa,this),15E3);this.qa()};
q.qa=function(){var a=this.na.bb,a=this.k.reading&&+this.k.reading||a>0;this.wb<this.Qa&&!a?this.wb++:ab()&&!a?this.wb++:(a?this.Qa=0:this.Nb(),this.wb=0,this.Na.push(0),this.Na.length>18&&this.Na.shift(),this.rc&&u()-this.Ua>=this.zb?this.terminate():this.Ca())};q.Tc=function(){this.Na.push(1);var a=0;t(this.Na,function(b){a+=b});a<3?(this.pc=g,this.Nb()):(this.terminate(),this.B.create("_SUPERFLY_lockout","1",600))};q.gb=k();q.Td=function(){var a=Fc(this);this.eb=Math.max(this.eb,a)};
function Fc(a){return Math.floor(yb(!!a.k.scrollElement))}q.Nb=function(){var a=this.Qa;this.Qa=a=a?Math.min(a*2,16):1};q.tb=function(){this.gb();this.terminate()};q.Gb=function(){this.yb=g;this.kc=j;this.da();this.ob()};function Ac(a){if(a.k[ac])return g;if(Gc(a))return j;a=document.referrer.indexOf("://"+r.location.hostname+"/");return a!=-1&&a<9}
function Gc(a){var b=a.k.referrerOverrideQueryParam,c="";t(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}function Bc(a){a=a.k[ac]||Gc(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=ub(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=J(b.pathname),a=vb(b)}return encodeURIComponent(a)}
function Hc(a){a=a.k[$b].slice(0,200);return encodeURIComponent(a)}function zc(a){a=[Bc(a),Ab("Width"),Ab("Height")];return ra(a)}function Ic(a){var b=[],c=a.B.N("_chartbeat4");c&&(t(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.B.remove("_chartbeat4"));return b}function Dc(a){var b=a.B.N("_cb_svref",g)||Bc(a)||"null";b==="null"&&(b=Ac(a)?"internal":"external",a.B.create("_cb_svref",b,1800,g));return b}function Cc(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?h:a[1]}
function Ec(){var a=r.performance&&r.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ka(b)&&b?Ka(a)&&a>b?a-b:u()-b:-1}q.terminate=function(){this.na.terminate();Jb(z,this.od);this.Db!==e&&Ja(r,"load",this.Db);eb(this.vb);vc().d=e;vc().n=e};q.za=function(){this.terminate();Ja(r,"pagehide",this.ic);this.ic=this.Db=this.B=this.Na=this.k=h;this.na.za();this.na=h;xc.la.za.call(this)};function Jc(a){for(var b=uc("m")||[];b.length;)a(b.shift());a={push:a};vc().m=a};function Kc(a){var b=a.offsetLeft,c=a.offsetTop,d=Lc(a);b+=d.x;c+=d.y;for(var f=j,d=a.offsetParent;a&&a!==e&&a!==document.body;){if(a===d)d=Lc(a),b+=a.offsetLeft+d.x,c+=a.offsetTop+d.y,d=a.offsetParent;if(Mc(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function Mc(a,b){var c={},d,f;r.getComputedStyle?d=r.getComputedStyle(a,h):a.currentStyle?f="currentStyle":a.style&&(f="style");t(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[f][b]});return c}var Nc=/matrix(3d)?\((.*)\)/;function Lc(a){var b={x:0,y:0},a=Mc(a,["transform"]).transform;if(!La(a))return b;var c=a.match(Nc);if(!c)return b;var a=c[2].split(", "),d;w(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};function Oc(){var a=r.location.href,a=a.replace(/-{2,}/g,"-"),a=ub(a);a.pathname=J(a.pathname);return a}
function Pc(a){var b=H.N("_chartbeat6");if(!b)return h;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var f,i=Oc(),l=vb(i);t(b,function(a,b){var i=a.split(","),n=Za(l,decodeURIComponent(i[0]));if(n===0)return c=i,d=b,j;if(f===e||n<f)f=n,c=i,d=b})}b.splice(d,1);H.create("_chartbeat6",b.join("::"),60,a.path?a.path:"/",a.domain?a.domain:"");var a=[],b=decodeURIComponent(c[0]),i=decodeURIComponent(c[1]),o=c[2];c.splice(0,3);for(var n=c.length/3,D=0;D<n;D++){var G=D*3+2;a.push({Le:b,
origin:i,Aa:o,Ta:G<c.length?c[G]:"",Ad:c[D*3],De:c[D*3+1]})}return a}function Qc(a){var b=a.topStorageDomain,a=a[C],c=r.location.hostname;return b?b:Rc(c,a)?a:c.replace(/^www\./,"")}function Rc(a,b){if(a===b)return g;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return g}function Sc(a,b,c,d,f){this.Cd=a;this.Bd=b;this.Ee=c;this.Aa=d;this.Ta=f}
function Tc(a){var b=a.d,c=h;if(b!==h){var d={};b.s&&t(b.s,function(a,b){d[b]=typeof a==="string"?{Cc:a,Ta:""}:{Cc:a.chosenVariant,Ta:a.specificLocation}});c={$c:d,Aa:b.g,Qc:b.m}}return{status:a.s,data:c,code:a.c,message:a.m}};function Uc(a,b){for(var c=b||document.documentElement,d=[],f=h,i=a,l,o,n,D,G,R;i&&i!==c;){l=i.nodeName.toLowerCase();f=i;o=f.nodeName;if((i=i.parentNode)&&i!==document.documentElement){n=i.children;D=0;for(G=0,R=n.length;G<R;G++){if(f===n[G]){l+="["+(1+G-D)+"]";break}n[G].nodeName!==o&&D++}}d.unshift(l)}return d.join("/")};function Vc(){this.ed="_t_";this.Gc=this.bd=cb;xc.call(this)}ea(Vc,xc);q=Vc.prototype;
q.da=function(){Vc.la.da.call(this);cc(this.k);var a=!!this.k[Yb],b=oc(!!this.k[Zb]&&a);F(this.k,"mabServer","mabping.chartbeat.net");F(this.k,$b,document.title);F(this.k,C,b);this.k[B]=this.k[B]?tc(this.k[B]):lc(a);this.ma=x(b);this.k[C]=x(this.k[C]);this.Be=Qc(this.k);this.$a=this.xb=j;this.Jc=[];var c=this,a=Pc({domain:"."+this.Be,path:this.k.cookiePath||"/"});if(a!==h)this.xb=g,t(a,function(a){c.Jc.push(new Sc(a.origin,a.Ad,a.De,a.Aa,a.Ta))});this.Rc=0;this.Hb=h;Jc(v(this.Md,this))};
q.Ca=function(){var a=this.na.Xa,b=Wc(this),c,d=this;this.xb&&t(this.Jc,function(f){c=b+"&x="+f.Bd+"&v="+f.Ee+"&ml="+f.Aa+"&xo="+f.Cd+"&e="+a+"&sl="+f.Ta;d.jb(c)});!this.$a&&this.Hb&&Xc(this,this.Hb);this.$a=g};q.tc=function(){this.hb=Ec();A.da();if(this.xb)this.vb=hb(v(this.qa,this),500);this.qa()};q.qa=function(){var a,b;this.$a?(a=this.na.Xa,b=this.Rc*15,a-b>=15&&(this.Ca(),this.Rc+=1),a>=45&&this.terminate()):this.Ca()};
function Wc(a){var b=a.k;return Qa()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b[C])+"&p="+encodeURIComponent(b[B])+"&d="+encodeURIComponent(a.ma)+"&u="+a.lb+"&c="+Math.round((u()-a.Ua)/600)/100+"&V=147"}q.gb=k();q.ze=function(a){a=Tc(a);this.$a?Xc(this,a):this.Hb=a};
function Xc(a,b){var c=Wc(a),d=b.status,f=b.data;if(d=="s"&&f!==h){var i=v(a.jb,a);Ra(f.$c)&&t(f.$c,function(a,b){i(c+"&x="+b+"&v="+a.Cc+"&ml="+f.Aa+"&sl="+a.Ta+"&e=-1")});Na(f.Qc)?t(f.Qc,function(a){i(c+"&me=3&ml="+f.Aa+"&x="+a)}):Na(f.Rd)&&t(f.Rd,function(a){i(c+"&me=5&ml="+f.Aa+"&x="+a)})}else d=="e"&&a.jb(c+"&me="+b.code)}
q.Md=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],f=a.shift();f==="t"?this.ze.apply(this,a):f==="v"?this.Zc.apply(this,a):f==="sv"?this.ve.apply(this,a):f==="ev"&&this.Zc.apply(this,a)}};q.tb=function(){this.Gc();Vc.la.tb.call(this)};q.Gb=function(){vc().m=[];this.bd();Vc.la.Gb.call(this)};q.ve=function(a){this.bd=a};q.Zc=function(a){this.Gc=a};q.terminate=function(){this.Me=e;this.Hb=h;this.$a=this.xb=e;Vc.la.terminate.call(this)};fc(r._sf_async_config||{});if(!H.N("cb_optout")&&!r.pSUPERFLY_mab){var Yc=new Vc,Zc={};Zc.evps=v(Yc.tb,Yc);Zc.svps=v(Yc.Gb,Yc);r.pSUPERFLY_mab=Zc;Yc.ob()};var $c,ad,bd;
function cd(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);dd();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=w(e)?e:{},b.src=a,a=Eb("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],w(e)?e.appendChild(a):b&&b.appendChild(a)}}
function dd(){gb(ad);ad=e;Ja(r,"message",cd);bd&&bd.parentNode&&bd.parentNode.removeChild(bd);bd=e};var ed=/^https?:\/\/([^/]*\.)?chartbeat\.com\/publishing\/hud2\/launch\//;function fd(){var a=r._sf_async_config&&r._sf_async_config.domain;if(a&&!$c){$c=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);Ia(r,"message",cd);ad=fb(dd,1E4);var b=w(e)?e:{};b.src=a;a=Eb("iframe",b);a.style.display="none";w(e)?e.appendChild(a):document.body&&document.body.appendChild(a);bd=a}}
function gd(){var a=I.ga(g);return a?(a.setItem("_cb_ip","1"),a.removeItem("_cb_hud_collapsed"),g):j}function hd(a){/[\/.]chartbeat\.com$/.test(a.origin)&&String(a.data).indexOf("_cb_ip")==0&&gd()&&(a.source.postMessage(1,a.origin),Gb(fd),Ja(r,"message",hd))};function id(a,b){this.jd=b;this.hd=a[Yb];this.gd=a[Zb];this.Ba=a[B];this.Ia=a[$b];this.Ec=a[C];this.Fe=a[ac];this.Bc=(this.ra=mc())?this.ra.hostname:"";this.pb=this.ra?J(this.ra.pathname)+this.ra.search+this.ra.hash:"";this.Yc=lc(j);this.re=oc(j);var c=wb("property","meta",h,"og:url");this.fb=(this.Ra=c&&c.length?ub(c[0].content):h)?J(this.Ra.pathname)+this.Ra.search+this.Ra.hash:"";this.Sd=this.Ra?this.Ra.hostname:"";this.Sb=document.title||"";var d;if((c=wb("property","meta",h,"og:title"))&&c.length)d=
c[0].content;this.Bb=d;var f;if((d=wb("property","meta",h,"twitter:title"))&&d.length)f=d[0].content;this.kb=f;f=!!this.hd;d=this.hd!==e;var c=!!this.gd,i=this.gd!==e,l=!!this.ra,o;o=x(this.Bc);var n=x(this.re);o=o===n;var n=!!this.fb,D=!this.ra?j:this.pb===this.fb,G=this.pb===this.Yc,R;R=this.pb;var U=Ea(this.Yc);R=R===U;var U=!!this.Sb,ha=!!this.Bb,ca=!!this.kb,L=this.Sb===this.Bb,E=!this.kb?j:this.Sb===this.kb,ja=!this.Bb||!this.kb?j:this.Bb===this.kb,ka=!!this.Ia,Ld=!!this.Ba,Md=this.Ba?this.Ba.charAt(0)!==
"/":j,Nd=!this.ra?j:this.Ba===this.pb,Od=!this.fb?j:this.Ba===this.fb,Pd=!this.ra?j:this.Ec===x(this.Bc),Qd=!this.fb?j:this.Ec===x(this.Sd),Rd=!!this.jd,Sd=this.jd?j:!!this.Fe,Td=Qa()==="https:",Ud=!!XMLHttpRequest,za;this.Ba?(za=Fa(this.Ba),za=za!==Ea(za)):za=j;f=[f,d,c,i,l,o,n,D,G,R,U,ha,ca,L,E,ja,ka,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,za];d=1;for(i=c=0;i<f.length;i++)c|=f[i]&&d,d<<=1;this.ud=("00000000"+c.toString(16)).slice(-8)};function jd(){"postMessage"in window&&Ia(r,"message",v(this.Jd,this));xc.call(this);bc("_cbq",v(this.Xc,this))}ea(jd,xc);
jd.prototype.da=function(){jd.la.da.call(this);var a=this.lb;vc().u=a;a=this.Ea;vc().t=a;this.Qd=new id(this.k,this.yb);this.Mb=h;cc(this.k);var a=!!this.k[Yb],b=oc(!!this.k[Zb]&&a);F(this.k,"pingServer","ping.chartbeat.net");F(this.k,$b,document.title);F(this.k,C,b);this.k[B]=this.k[B]?tc(this.k[B]):lc(a);this.ma=x(b);this.k[C]=x(this.k[C]);this.qd=Ib(z,"c",this.Wd,this);this.rd=Ib(z,"r",this.Xd,this);this.Pa=h};jd.prototype.nd=function(a){this.Mb=a};
jd.prototype.gb=function(){this.B.update("_chartbeat4",["t="+this.Ea,"E="+this.na.Xa,"x="+Fc(this),"c="+Math.round((u()-this.Ua)/600)/100,"y="+Ab("Height"),"w="+zb()].join("&"),60,e,e,1)};var tb="h,p,u,d,g,g0,g1,g5,g3,g4,g6,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,sv,sr,sd,im".split(",");q=jd.prototype;
q.Ca=function(a){this.ib++;var b={};b.g=this.k.uid;b.g0=dc(this.k,"sections")||"No%20Section";b.g1=dc(this.k,"authors")||"No%20Author";b.g2=dc(this.k,"zone");b.g3=dc(this.k,"sponsorName");b.g4=dc(this.k,"type");!this.k.noCookies&&this.B.isSupported()?b.n=this.ac:b.nc=1;b.c=Math.round((u()-this.Ua)/600)/100;b.E=this.na.Xa;var c=Fc(this);this.eb=Math.max(this.eb,c);b.x=c;b.m=this.eb;b.y=Ab("Height");b.o=Ab("Width");b.w=zb();b.b=this.hb>0?this.hb:"";if(this.Lc&&!this.k.noCookies&&this.B.isSupported())b.f=
this.Lc;b[""]=ec(this.k);b.t=this.Ea;b.V=147;b.tz=(new Date).getTimezoneOffset();b.sn=this.ib;b.sv=this.ye;b.sr=this.xe;b.sd=this.we;c=this.na.bb;b.h=encodeURIComponent(this.k[C]);b.p=encodeURIComponent(this.k[B]);b.u=this.lb;b.d=encodeURIComponent(this.ma);b.j=Math.round((this.Qa+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;A.pd()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Ac(this);if(this.pc){this.pc=j;if(c)this.Pa=kd(this);b.i=Hc(this);var d=this.k.hudTrackable;d!==e&&(b.L=d?"1":
"0")}if(c){if(this.Pa){if(b.v=encodeURIComponent(this.Pa.path),b.K=ld(this.Pa),this.Pa.cc>1)b.l1=this.Pa.cc}else b.v=Bc(this);this.yb&&(b.vp=1)}else b.r=Bc(this);c=ib(b.v);vc().v=c;c=ib(b.r);vc().r=c;b.A=this.Mb?this.Mb:"";b._c=qb("utm_campaign",this.k.campaignTag);b._m=qb("utm_medium",this.k.mediumTag);b._x=qb("utm_source",this.k.sourceTag);b._y=qb("utm_content",this.k.contentTag);b._z=qb("utm_term",this.k.termTag);b.im=this.Qd.ud;d=this.k;c=d.idSync;if(qa(d[C]).toString()!==[-2029634429,-1659526092,
-2053164062,-1348054445,1670716250].toString())c=c?Xa(c):"";else{if(d=window.OBR&&window.OBR.extern&&window.OBR.extern.pvId)c=c?c:{},c.obr=d;c=Xa(c)}b._s=c;b.z=Ic(this);b.C=this.k.mobileApp?1:"";b.KK=a?ld(a):"";b.l=ic(this.B)?1:"";this.na.bb=0;if(this.k.alias)b.PA=encodeURIComponent(this.k.alias);else{a=md(r.location.href);if(a.search.length>0)a.search=nc(a.search);b.PA=encodeURIComponent(vb(a))}if(a=r.location.href.match(/[^?]+[?]([^#]+).*/))a=pb(a[1]),a.cb_rec&&(b.g5=encodeURIComponent(a.cb_rec));
b.g6=ob(this.k.uid);this.jb(Qa()+"//"+this.k.pingServer+"/ping?"+sb(b))};
q.Jd=function(a){var b=this.k,c=b.playerdomain||this.ma;if(ua(a.origin)===ua(c))if(c=a.data,La(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Xc(a));else if(c=="cbdata?"){var c="&u="+uc("u"),d="&t="+uc("t"),f="&v="+uc("v"),i="&r="+uc("r"),b="domain="+encodeURIComponent(b[C])+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b[B])+"&title="+Hc(this)+"&referrer="+Bc(this)+"&internal="+(Ac(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ma)+
c+d+f+i+"&utoken="+this.lb;a.source.postMessage(b,"*")}};q.Xc=function(a){var b=a[0],a=a[1];if(b==="_demo"&&this.k._demo)this.k._demo=this.k._demo+"%2C"+a;else if(a!==this.k[b]&&(this.k[b]=a,this.Qa=0,this.ib>0&&!this.ub)){var c=this.ib,d=this;this.ub=fb(function(){d.ub=h;d.ib===c&&d.Ca()},1E3)}};function md(a){a=a.replace(/-{2,}/g,"-");a=ub(a);a.pathname=J(a.pathname);return a}q.Wd=function(a){nd(this,a,"c")};q.Xd=function(a){nd(this,a,"r")};
function nd(a,b,c){if(a.rc&&u()-a.Ua>=a.zb)a.terminate();else{var d=b.href||"",d=md(d);if(d.protocol.indexOf("http")===0){var f=d.hostname!==r.location.hostname,d=vb(d),i=Bb(b,function(a){return a.id}),l=Uc(b,i),o="";a.k.moduleAttribute&&(o=(o=xb(b,a.k.moduleAttribute))?o.getAttribute(a.k.moduleAttribute):"",o=o.replace(/::/g,"-").substr(0,40));i?(l&&(l="/"+l),l="*[@id='"+i.id+"']"+l,i=Uc(b)):i=l;l=pa(l);i=pa(i);b=Kc(b);c={left:b.x,top:b.y,path:a.k[B],href:d,yc:l,Lb:i,xc:"",sc:c,cc:0,Ed:a.k[C],$b:o};
a.Ca(c);f||a.B.update("_chartbeat5",od(c),60,j,e,3,function(a){a=a.split("|");return a[2]+"|"+a[3]})}}}function ld(a){return[a.left,a.top,a.yc,encodeURIComponent(a.xc),a.sc,encodeURIComponent(a.href),a.Lb,a.$b].join("::")}function od(a){var b=encodeURIComponent(a.xc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.yc,b,a.sc,a.Lb,encodeURIComponent(a.Ed),a.$b].join("|")}
function kd(a){var b=a.B.N("_chartbeat5");if(!b)return h;var c=b.split("::"),b=c.length,d,f=h,i,l=md(r.location.href),o=vb(l);t(c,function(a,b){var c=a.split("|"),l=decodeURIComponent(c[3]);if(l){l=Ha(o,l);if(l===0)return d=c,f=b,j;else if(l===h)return g;if(i===e||l<i)i=l,d=c,f=b}});if(f===h)return h;c.splice(f,1);a.B.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),
yc:d[4]||"",xc:"",Lb:d.length>7?d[7]:"",sc:d.length>6?d[6]:"c",cc:b,$b:d[9]?d[9]:""}}q.terminate=function(){Jb(z,this.qd);Jb(z,this.rd);gb(this.ub);this.ub=h;jd.la.terminate.call(this)};var M="ct",N="s1";function O(a){this.a=a;this.F=this.D=j;this.q=u();this.fa()}q=O.prototype;q.fa=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.ea();this.a.on("play",v(this.ea,this));this.a.on("dispose",v(this.Zd,this));this.a.ready(v(this.ka,this))};q.ka=function(){this.D=g};q.ea=function(){this.F=g};q.Zd=function(){var a=r._cbv;a&&a.push&&a.push(["removePlayer",this.a])};q.J=function(){return this.D&&this.M()!==""};
q.Ub=function(){var a;this.a.cb_configs&&this.a.cb_configs[C]?a=this.a.cb_configs[C]:!a&&r._sf_async_config&&r._sf_async_config[C]&&(a=r._sf_async_config[C]);return a};q.Vb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&r._sf_async_config&&r._sf_async_config.uid&&(a=r._sf_async_config.uid);return a};q.M=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("name")?a.name:this.a.el().getAttribute("title"))||""};
q.H=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("id")?a.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};q.T=function(){return M};q.O=p("");q.aa=function(){var a=this.a.duration();return y(a)};q.G=function(){return!this.F?N:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};q.U=function(){var a=this.a.currentTime();return y(a)};q.S=p(-1);
q.$=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("thumbnail")?a.thumbnail:this.a.poster())||""};q.X=k();q.Q=k();q.ba=function(){return $a(this.q)};q.Y=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&r._sf_async_config&&r._sf_async_config.sections&&(a=r._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};
q.P=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&r._sf_async_config&&r._sf_async_config.authors&&(a=r._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};q.Z=p("BCN");O.prototype.getStrategyName=O.prototype.Z;O.prototype.isReady=O.prototype.J;O.prototype.getHost=O.prototype.Ub;O.prototype.getUid=O.prototype.Vb;O.prototype.getTitle=O.prototype.M;O.prototype.getVideoPath=O.prototype.H;
O.prototype.getContentType=O.prototype.T;O.prototype.getAdPosition=O.prototype.O;O.prototype.getTotalDuration=O.prototype.aa;O.prototype.getState=O.prototype.G;O.prototype.getCurrentPlayTime=O.prototype.U;O.prototype.getBitrate=O.prototype.S;O.prototype.getThumbnailPath=O.prototype.$;O.prototype.getPlayerType=O.prototype.X;O.prototype.getAutoplayType=O.prototype.Q;O.prototype.getViewStartTime=O.prototype.ba;O.prototype.getSections=O.prototype.Y;O.prototype.getAuthors=O.prototype.P;
O.verify=function(a){return a.controlBar!==e||a.cb_plugin_version!==e};function P(a){this.Ya=this.ma=e;this.D=j;this.Wc=this.Fc=-1;this.ua=h;this.a=a;this.F=j;this.jc=g;this.q=u();this.lc="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var d=a[c];if((d.indexOf("chartbeat")>=0||d.indexOf("localhost")>=0)&&d.indexOf(".js")>=0){this.lc=d;break}}if(this.lc){a=pb(this.lc);if(this.ma=a[C])this.ma=this.ma.replace(/^video@/,"");this.Ya=a.uid}a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);
b.getReady()?this.Uc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Uc,this))}q=P.prototype;
q.Uc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.Fc=Math.round(a)});b.getCurrentVideo(function(a){c.ua=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.ge,this));b.addEventListener(a.STOP,s(this.ie,this));b.addEventListener(a.COMPLETE,s(this.Yd,this));b.addEventListener(a.BEGIN,s(this.ea,this));this.D=g};q.ge=function(a){this.Wc=a.position;this.ya=this.jc=j};q.ie=function(){this.jc=g};
q.Yd=function(){this.ya=g};q.ea=function(){this.ya=j;if(!this.F)this.F=g};q.J=m("D");q.M=function(){var a="";this.ua&&(a=this.ua.displayName);return a};q.H=function(){var a="";this.ua&&(a="video@"+this.ma+"/"+this.ua.id);return a};q.T=function(){return M};q.O=p("");q.aa=m("Fc");q.G=function(){return!this.F?N:this.ya?"s4":this.jc?"s3":"s2"};q.U=function(){return y(this.Wc)};q.S=p(-1);q.$=function(){var a="";this.ua&&(a=this.ua.thumbnailURL);return a};q.X=k();
q.ba=function(){return isNaN(this.q)?0:Ya(this.q)};q.P=k();q.Y=function(){var a;this.ua&&(a=this.ua.tags);return a};q.Q=p("unkn");q.Z=p("BC");q.Ub=m("ma");q.Vb=m("Ya");P.prototype.isReady=P.prototype.J;P.prototype.getTitle=P.prototype.M;P.prototype.getVideoPath=P.prototype.H;P.prototype.getContentType=P.prototype.T;P.prototype.getAdPosition=P.prototype.O;P.prototype.getTotalDuration=P.prototype.aa;P.prototype.getState=P.prototype.G;P.prototype.getCurrentPlayTime=P.prototype.U;
P.prototype.getBitrate=P.prototype.S;P.prototype.getThumbnailPath=P.prototype.$;P.prototype.getPlayerType=P.prototype.X;P.prototype.getViewStartTime=P.prototype.ba;P.prototype.getAuthors=P.prototype.P;P.prototype.getSections=P.prototype.Y;P.prototype.getAutoplayType=P.prototype.Q;P.verify=function(a){return a===window.brightcove};P.prototype.getStrategyName=P.prototype.Z;P.prototype.getHost=P.prototype.Ub;P.prototype.getUid=P.prototype.Vb;function Q(a){this.a=a;this.F=this.D=j;this.q=u();this.Pc=this.xa=this.Da=e;this.Ia=this.Ha="";this.Zb=e;this.fa()}var pd=/url\(['"]?([^'"\)]*)['"]?\)/;q=Q.prototype;
q.Tb=function(){var a=this.Pc=this.H();if(this.a.conf&&(this.Ia=this.a.conf.title?this.a.conf.title:"",this.Ha=this.a.conf.poster?this.a.conf.poster:"",this.Ia&&this.Ha))return g;var b=wb("name","param"),c=e;t(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===e&&(b=wb("src","video"),t(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=xb(c,"data-swf")||xb(c,"poster");if(b===j)return j;
this.Ha=b.attributes.poster&&b.attributes.poster.value;if(!this.Ha){var d=b.style.background;if(d&&(d=d.match(pd)))this.Ha=d[1]}this.Ia=b.title;if(this.Zb!==e)clearInterval(this.Zb),this.D=g;return g};function qd(a){if(a.Pc!==a.H())a.Ha="",a.Ia="",a.Tb()}q.fa=function(){this.a.ready?this.ka():this.a.bind("ready",s(this.ka,this));this.a.bind("resume",s(this.ea,this));this.a.playing&&this.ea()};q.ka=function(){this.Tb()===j?this.Zb=setInterval(s(this.Tb,this),1E3):this.D=g};
q.ea=function(){if(!this.F)this.F=g};q.J=m("D");q.M=function(){qd(this);return this.Ia};q.H=function(){return this.a.video.url||this.a.video.src};q.T=function(){return M};q.O=p("");q.aa=function(){return this.a.video.duration&&this.a.video.duration*1E3};q.G=function(){return!this.F?N:this.a.Ne?"s4":this.a.paused?"s3":"s2"};q.U=function(){return y(this.a.video.time)};q.S=p(-1);q.$=function(){qd(this);return this.Ha};q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:Ya(this.q)};q.Y=m("Da");
q.P=m("xa");q.Z=p("FP");Q.prototype.getStrategyName=Q.prototype.Z;Q.prototype.isReady=Q.prototype.J;Q.prototype.getTitle=Q.prototype.M;Q.prototype.getVideoPath=Q.prototype.H;Q.prototype.getContentType=Q.prototype.T;Q.prototype.getAdPosition=Q.prototype.O;Q.prototype.getTotalDuration=Q.prototype.aa;Q.prototype.getState=Q.prototype.G;Q.prototype.getCurrentPlayTime=Q.prototype.U;Q.prototype.getBitrate=Q.prototype.S;Q.prototype.getThumbnailPath=Q.prototype.$;Q.prototype.getPlayerType=Q.prototype.X;
Q.prototype.getAutoplayType=Q.prototype.Q;Q.prototype.getViewStartTime=Q.prototype.ba;Q.prototype.getSections=Q.prototype.Y;Q.prototype.getAuthors=Q.prototype.P;Q.verify=function(a){return window.flowplayer&&a.engine&&a.engine.engineName};function S(a){this.a=a;this.Kb=this.F=this.D=j;this.q=u();this.xa=this.Da=e;this.fa()}q=S.prototype;q.fa=function(){this.a.readyState>0&&this.ka();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.ea();this.a.addEventListener("canplay",v(this.ka,this));var a=v(this.ea,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",v(this.qe,this))};q.ka=function(){this.D=g};q.ea=function(){this.F=g;this.Kb=j};
q.qe=function(){this.Kb=g};q.J=m("D");q.M=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};q.H=function(){return this.a.currentSrc||""};q.T=function(){return M};q.O=p("");q.aa=function(){return y(this.a.duration)};q.G=function(){return!this.F?N:this.a.ended||this.Kb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.Kb?"s3":"s2"};q.U=function(){return y(this.a.currentTime)};q.S=p(-1);q.$=function(){return this.a.poster||""};q.X=k();
q.Q=function(){return this.a.autoplay?"auto":"man"};q.ba=function(){return $a(this.q)};q.Y=m("Da");q.P=m("xa");q.Z=p("H5");S.prototype.getStrategyName=S.prototype.Z;S.prototype.isReady=S.prototype.J;S.prototype.getTitle=S.prototype.M;S.prototype.getVideoPath=S.prototype.H;S.prototype.getContentType=S.prototype.T;S.prototype.getAdPosition=S.prototype.O;S.prototype.getTotalDuration=S.prototype.aa;S.prototype.getState=S.prototype.G;S.prototype.getCurrentPlayTime=S.prototype.U;
S.prototype.getBitrate=S.prototype.S;S.prototype.getThumbnailPath=S.prototype.$;S.prototype.getPlayerType=S.prototype.X;S.prototype.getAutoplayType=S.prototype.Q;S.prototype.getViewStartTime=S.prototype.ba;S.prototype.getSections=S.prototype.Y;S.prototype.getAuthors=S.prototype.P;S.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==h;return b&&!a};function T(a){this.a=a;this.F=this.ya=this.D=j;this.q=u();this.cb=j;this.fa()}q=T.prototype;q.fa=function(){function a(a,f){f=s(f,c);if(aa(b.on)=="function")b.on(a,f);else{var i="on"+a.substr(0,1).toUpperCase()+a.substr(1);if(aa(b[i])=="function")b[i](f)}}var b=this.a,c=this;a("ready",this.ka);a("time",this.ke);a("complete",this.le);a("adStarted",this.va);a("adPlay",this.va);a("adImpression",this.va);a("adTime",this.va);a("adComplete",this.ec);a("adSkipped",this.ec);a("adError",this.ec)};
q.ka=function(){this.D=g};q.ke=function(){this.ya=j;this.F=g;this.cb=j};q.le=function(){this.ya=g};q.va=function(){this.cb=this.F=g};q.ec=function(){this.cb=j};q.J=function(){this.a.getState();return this.D||this.a.getState()!==e};q.M=function(){var a=rd(this);return!a?"":a.title};function rd(a){if(a.a.getPlaylistIndex===e)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return h;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?h:b[a]}
q.H=function(){var a=rd(this);return!a?"":a.mediaid||a.file};q.T=function(){return this.cb?"ad":M};q.O=p("");q.aa=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};q.G=function(){if(!this.F)return N;if(this.cb)return"s2";if(this.ya)return"s4";var a=this.a.getState();return a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};q.U=function(){var a=this.a.getPosition();return y(a)};q.S=p(-1);q.$=function(){var a=rd(this);return!a?"":a.image};q.X=k();q.ba=function(){return isNaN(this.q)?0:Ya(this.q)};
q.P=k();q.Y=k();q.Q=p("unkn");q.Z=p("JW");T.prototype.getStrategyName=T.prototype.Z;T.prototype.isReady=T.prototype.J;T.prototype.getTitle=T.prototype.M;T.prototype.getVideoPath=T.prototype.H;T.prototype.getContentType=T.prototype.T;T.prototype.getAdPosition=T.prototype.O;T.prototype.getTotalDuration=T.prototype.aa;T.prototype.getState=T.prototype.G;T.prototype.getCurrentPlayTime=T.prototype.U;T.prototype.getBitrate=T.prototype.S;T.prototype.getThumbnailPath=T.prototype.$;
T.prototype.getPlayerType=T.prototype.X;T.prototype.getViewStartTime=T.prototype.ba;T.prototype.getAuthors=T.prototype.P;T.prototype.getSections=T.prototype.Y;T.prototype.getAutoplayType=T.prototype.Q;T.verify=function(a){return w(a.id)&&w(a.registerPlugin)};function V(a){this.a=a;this.nb="";this.ca=N;this.pa=M;this.ja="";this.q=u();this.fa()}q=V.prototype;q.fa=function(){this.a.kBind("playerStateChange.cb",s(this.pe,this));this.a.kBind("playerUpdatePlayhead.cb",s(this.fe,this));this.a.kBind("playerPlayEnd.cb",s(this.oe,this));this.a.kBind("adStart.cb",s(this.va,this));this.a.kBind("adEnd.cb",s(this.dc,this));this.a.kBind("switchingChangeComplete.cb",s(this.je,this))};
q.pe=function(a){switch(a){case "playing":this.ca="s2";break;case "buffering":this.ca="s3";break;case "paused":this.ca="s3"}};q.fe=function(){this.ca="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};q.oe=function(){this.ca="s4"};q.va=function(a){this.pa="ad";switch(a){case "pre":this.ja="a1";break;case "post":this.ja="a3";break;case "mid":this.ja="a2";break;case "main":this.ja="a5"}};q.dc=function(){this.pa=M};q.je=function(a,b){this.vd=b};
q.J=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=h};q.M=function(){return this.a.evaluate("{mediaProxy.entry.name}")};q.H=function(){if(!this.J())return this.nb;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.nb=a)||""};q.T=m("pa");q.O=m("ja");q.aa=function(){var a=this.a.evaluate("{duration}");return y(a)};q.G=m("ca");q.U=function(){var a=this.a.evaluate("{video.player.currentTime}");return y(a)};q.S=m("vd");
q.$=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};q.X=k();q.Q=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};q.ba=function(){return isNaN(this.q)?0:$a(this.q)};q.Y=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
q.P=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};q.Z=p("KT");V.prototype.getStrategyName=V.prototype.Z;V.prototype.isReady=V.prototype.J;V.prototype.getTitle=V.prototype.M;V.prototype.getVideoPath=V.prototype.H;V.prototype.getContentType=V.prototype.T;V.prototype.getAdPosition=V.prototype.O;V.prototype.getTotalDuration=V.prototype.aa;V.prototype.getState=V.prototype.G;V.prototype.getCurrentPlayTime=V.prototype.U;V.prototype.getBitrate=V.prototype.S;
V.prototype.getThumbnailPath=V.prototype.$;V.prototype.getPlayerType=V.prototype.X;V.prototype.getAutoplayType=V.prototype.Q;V.prototype.getViewStartTime=V.prototype.ba;V.prototype.getSections=V.prototype.Y;V.prototype.getAuthors=V.prototype.P;V.verify=function(a){return typeof a.kBind=="function"};function W(a){this.a=a;this.D=j;this.ca=N;this.pa=M;this.ja=this.nb="";this.q=u();this.fa()}q=W.prototype;
q.fa=function(){this.a.addEventListener(this.a.Event.Core.PLAY,s(this.ea,this));this.a.addEventListener(this.a.Event.Core.PAUSE,s(this.ne,this));this.a.addEventListener(this.a.Event.Core.PLAYBACK_ENDED,s(this.me,this));this.a.addEventListener(this.a.Event.AD_BREAK_START,s(this.va,this));this.a.addEventListener(this.a.Event.AD_BREAK_END,s(this.dc,this));this.a.addEventListener(this.a.Event.Core.SOURCE_SELECTED,s(this.ka,this))};q.ea=function(){this.ca="s2"};q.ne=function(){this.ca="s3"};
q.me=function(){this.ca="s4"};q.J=function(){return this.D||this.a.config.sources.metadata&&this.a.config.sources.metadata.name};q.va=function(a){this.ca="s3";a=a.payload.adBreak.type;this.pa="ad";switch(a){case "preroll":this.ja="a1";break;case "postroll":this.ja="a3";break;case "midroll":this.ja="a2"}};q.dc=function(){this.pa=M};q.ka=function(){this.D=g};q.M=function(){return this.a.config.sources.metadata?this.a.config.sources.metadata.name:""};
q.H=function(){if(!this.J())return this.nb;var a=this.a.config.sources.id;return(this.nb=a)||""};q.T=m("pa");q.O=m("ja");q.aa=function(){if(typeof this.a.config.sources.duration!=="undefined")return y(this.a.config.sources.duration)};q.G=m("ca");q.U=function(){return y(this.a.currentTime)};q.S=k();q.$=function(){return this.a.poster};q.X=k();
q.Q=function(){var a=this.a.config.playback.autoplay,b=this.a.playlist._playlist._activeItemIndex;return this.a.playlist.options.autoContinue&&b>0?"cont":a?"auto":"man"};q.ba=function(){return isNaN(this.q)?0:$a(this.q)};q.Y=function(){if(this.a.config.sources.metadata&&this.a.config.sources.metadata.tags.length)return this.a.config.sources.metadata.tags.split(", ")};q.P=k();q.Z=p("KT7");W.prototype.getStrategyName=W.prototype.Z;W.prototype.isReady=W.prototype.J;W.prototype.getTitle=W.prototype.M;
W.prototype.getVideoPath=W.prototype.H;W.prototype.getContentType=W.prototype.T;W.prototype.getAdPosition=W.prototype.O;W.prototype.getTotalDuration=W.prototype.aa;W.prototype.getState=W.prototype.G;W.prototype.getCurrentPlayTime=W.prototype.U;W.prototype.getBitrate=W.prototype.S;W.prototype.getThumbnailPath=W.prototype.$;W.prototype.getPlayerType=W.prototype.X;W.prototype.getAutoplayType=W.prototype.Q;W.prototype.getViewStartTime=W.prototype.ba;W.prototype.getSections=W.prototype.Y;
W.prototype.getAuthors=W.prototype.P;W.verify=function(a){return a.Event&&a.Event.Core};function X(a){this.Ac=e;this.a=a;this.Oc=e;this.D=j;this.La=e;this.F=j;this.xa=this.Da=this.q=e;this.Ac=r.OO;this.Oc=this.a.mb;this.q=u();this.fa()}q=X.prototype;
q.fa=function(){var a=this.Oc,b=this.Ac.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.ka,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.Vd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.ea,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.Ud,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.ee,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.$d,this))};q.ka=function(){this.D=g};
q.Vd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.La=a===0?"a1":sd(a,b)?"a3":"a2"};q.ea=function(){this.F=g};q.Ud=function(){this.La=e};q.ee=k();q.J=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.D=g;return this.D};q.M=function(){var a=this.a.getItem();return a?a.title:""};
q.H=function(){var a=this.a.getEmbedCode&&this.a.getEmbedCode();if(a)return a;a=this.a.getItem()||{};return a.embed_code||a.embedCode||this.a.embedCode||""};q.T=function(){return this.La===e?M:"ad"};q.O=function(){return this.La?this.La:""};q.aa=function(){var a=this.a.getItem(),a=a&&a.duration||this.a.getDuration()*1E3;return a===-1||!isFinite(a)?-1:a};
q.G=function(){if(!this.F)return N;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return sd(a,b)?"s4":"s2"};function sd(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}q.$d=function(){this.La=e};q.U=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};
q.S=function(){var a=this.a.getCurrentBitrate&&this.a.getCurrentBitrate();return a?a.bitrate:0};q.$=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:$a(this.q||0)};q.Y=m("Da");q.P=m("xa");q.Z=p("OO");X.prototype.getStrategyName=X.prototype.Z;X.prototype.isReady=X.prototype.J;X.prototype.getTitle=X.prototype.M;X.prototype.getVideoPath=X.prototype.H;X.prototype.getContentType=X.prototype.T;
X.prototype.getAdPosition=X.prototype.O;X.prototype.getTotalDuration=X.prototype.aa;X.prototype.getState=X.prototype.G;X.prototype.getCurrentPlayTime=X.prototype.U;X.prototype.getBitrate=X.prototype.S;X.prototype.getThumbnailPath=X.prototype.$;X.prototype.getPlayerType=X.prototype.X;X.prototype.getAutoplayType=X.prototype.Q;X.prototype.getViewStartTime=X.prototype.ba;X.prototype.getSections=X.prototype.Y;X.prototype.getAuthors=X.prototype.P;
X.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("isAdPlaying")};function Y(a){this.a=a;this.ia=h;this.ab="";this.ca=N;this.pa=M;this.ja="";this.q=u();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}q=Y.prototype;q.Pd=function(a){this.fa(a.controller)};
q.fa=function(a){a.addEventListener("OnLoadRelease",v(this.Sc,this));a.addEventListener("OnLoadReleaseUrl",v(this.Sc,this));a.addEventListener("OnReleaseStart",v(this.he,this));a.addEventListener("OnMediaPlay",v(this.be,this));a.addEventListener("OnMediaStart",v(this.de,this));a.addEventListener("OnMediaPause",v(this.hc,this));a.addEventListener("OnMediaComplete",v(this.ae,this));a.addEventListener("OnMediaError",v(this.hc,this));a.addEventListener("OnMediaBuffer",v(this.hc,this));a.addEventListener("OnMediaPlaying",
v(this.ce,this))};q.Sc=function(a){if(a.data&&a.data.title)this.ia=a.data;if(a.data&&a.data.guid)this.ab=a.data.guid};q.he=function(a){t(a.data.clips,v(function(a){if(a=a.baseClip.guid)return this.ab=a,j},this));if(this.ab&&a.data.release&&a.data.release.title)this.ia=a.data.release};q.be=function(){this.ca="s2"};q.de=function(a){this.ca="s2";a=a.data.baseClip;a.isAd?(this.pa="ad",this.ja=a.isMid?"a2":"a1"):(this.pa=M,this.ja="")};q.hc=function(){if(this.ca!=N)this.ca="s3"};
q.ae=function(){this.ca="s4"};q.ce=function(a){this.zd=a.currentTime};q.J=function(){return this.ia!=h};q.M=function(){return this.ia.title};q.H=function(){return!this.ab?"":this.ab};q.T=m("pa");q.O=m("ja");q.aa=function(){return this.ia.duration};q.G=m("ca");q.U=m("zd");q.S=function(){return this.ia.bitrate};q.$=function(){return this.ia&&this.ia.defaultThumbnailUrl?this.ia.defaultThumbnailUrl:this.ia.pid?"http://link.theplatform.com/s/ngc/"+this.ia.pid+"?format=poster&height=70&width=95":""};
q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:this.q===e?0:u()-this.q};q.Y=function(){var a=this.ia.keywords?this.ia.keywords.split(","):[],b=[];t(this.ia.categories?this.ia.categories:[],function(a){b.push(encodeURIComponent(a.name))});t(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};q.P=k();q.Z=p("TP");Y.prototype.initialize=Y.prototype.Pd;Y.prototype.getStrategyName=Y.prototype.Z;Y.prototype.isReady=Y.prototype.J;Y.prototype.getTitle=Y.prototype.M;
Y.prototype.getVideoPath=Y.prototype.H;Y.prototype.getContentType=Y.prototype.T;Y.prototype.getAdPosition=Y.prototype.O;Y.prototype.getTotalDuration=Y.prototype.aa;Y.prototype.getState=Y.prototype.G;Y.prototype.getCurrentPlayTime=Y.prototype.U;Y.prototype.getBitrate=Y.prototype.S;Y.prototype.getThumbnailPath=Y.prototype.$;Y.prototype.getPlayerType=Y.prototype.X;Y.prototype.getAutoplayType=Y.prototype.Q;Y.prototype.getViewStartTime=Y.prototype.ba;Y.prototype.getSections=Y.prototype.Y;
Y.prototype.getAuthors=Y.prototype.P;Y.verify=function(a){return typeof a.controller!=="undefined"};function td(a,b){this.a=a;this.fd=b;this.Oa=window.location!=window.parent.location;this.Vc=j;this.Ae=u();this.ed="_v_";this.ta={};xc.call(this)}ea(td,xc);var ud=r.QUICK_TEST?1E4:6E4,vd="autoDetect",wd={Je:"title",Ke:"videopath",Ie:"thumbnailpath"},xd={};q=td.prototype;
q.da=function(){this.ac=(this.Sa=this.B.N("_chartbeat3"))?0:1;this.wc=this.qc=g;this.Qb=j;this.Fb=this.mc=this.Hc=this.Ga=e;this.Ma=15E3;this.qb=e;this.rb=this.sb=0;this.Rb=j;this.se=this.uc=this.Jb=0;this.oc=j;if(!this.Sa||this.Sa.length===0)this.Sa=pa(zc(this),3);this.B.create("_chartbeat3",this.Sa,34128E3);var a;(a=this.fd)&&Ma(a)?(this.ha=new a(this.a),a=g):a=j;if(a){a=!!this.k[Yb];var b=oc(!!this.k[Zb]&&a);F(this.k,"pingServer","ping.chartbeat.net");F(this.k,$b,document.title);F(this.k,C,b);
this.k[B]=this.k[B]?tc(this.k[B]):lc(a);this.k[C]=x(this.k[C]);this.ha.getPlayerType&&F(this.k,"video_type",this.ha.getPlayerType());this.Hc=setInterval(v(this.wd,this),1E3);if(this.Oa===g)this.Ab=v(this.Kd,this),Ia(window,"message",this.Ab),this.qb=setInterval(this.te,1E3);td.la.da.call(this)}};q.Nb=k();
q.qa=function(){if(this.ha){if(!yd(this))this.wc=g;if(!this.wc)return u()-this.Ua>=this.zb&&clearInterval(this.Ga),td.la.qa.call(this);if(this.ha.isReady())this.Qb=this.wc=j,this.mc=zd(this),Ad(this),this.Ga=setInterval(v(this.Pb,this),100),td.la.qa.call(this);else if(!this.Qb){this.Qb=g;if(this.se++>150)throw"Error: Video strategy never reported its ready state";Bd(this,100)}}};
q.Ca=function(){if(this.ha){var a=this.k,b=this.ha,c=b.getState(),d=yd(this),f=this.Oa?[]:r._cbq||(r._cbq=[]),i=b.getViewStartTime(),l=Cd(this),o=b.getAutoplayType?b.getAutoplayType():e,i=i===-1?-1:i/1E3,l=l?encodeURIComponent(l):e;if(!xd.path||xd.path===d||c==="s2"&&xd.state!=="s2")switch(xd={path:d,state:c},f.push(["_vi",Pa(Dd(this))]),f.push(["_vp",d]),f.push(["_vdd",Pa(Ed(this))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),b.getAdPosition&&f.push(["_vap",
b.getAdPosition()]),f.push(["_vtn",Pa(Cd(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case N:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=Fd(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vcs",this.Rb?"1":"0")+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",i)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",l)+Z("_vaup",o||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.uc)+Z("c",Math.round(Ya(this.Ae)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.Jb+"&j="+(this.Ma/1E3+15)+Gd(this)+"&tz="+(new Date).getTimezoneOffset()+(ic(this.B)?"&l=1":"")+"&_";this.Oa===g&&t(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.jb(a)}};function Z(a,b){return b!==e&&b!==""?"&"+a+"="+b:""}q.gb=function(){this.B.update("_cb_cp",this.Ea,60,j,",")};function Gd(a){var b=a.B.N("_cb_cp");a.B.remove("_cb_cp");return b?"&D="+b:""}
function Hd(a){return a.k.subdomain?a.k.subdomain:x(r.location.hostname)}function Ed(a){var b=a.k,a=a.ha,b=b.videodomain||a.getHost&&a.getHost()||b[C];return"video@"+(b&&b.replace(/^video@/,""))}function yd(a){var b=a.ta.videopath;if(b)return b;if(a.k.videoPathHash){if(a=Dd(a))return pa(a)}else return a.ha.getVideoPath();return""}function Dd(a){return a.ta.title||a.ha.getTitle()}function Cd(a){return a.ta.thumbnailpath||a.ha.getThumbnailPath()}
function Fd(a){var b=a.k,c=a.ha,d=c.getUid&&c.getUid()||b.uid,f=Pa(Ed(a)),i="",l=a.hb?"&b="+a.hb:"",o,n=a.k[B];o=a.k.useSubDomains!==j&&n&&n.substr(0,1)==="/"?Hd(a)+n:n;var n=c.getSections&&c.getSections(),D=c.getAuthors&&c.getAuthors(),G=b.sections?"&g0="+encodeURIComponent(b.sections):"",R=b.authors?"&g1="+encodeURIComponent(b.authors):"",n=n===e||b.videoPageGroups?G:"&g0="+encodeURIComponent(n.join(",")),D=D===e||b.videoPageGroups?R:"&g1="+encodeURIComponent(D.join(",")),R="",G=yd(a);if(a.Fb===
e)a.Fb=G;else if(G!=a.Fb)R=Z("D",a.Ea),a.Ea=pa(zc(a)),a.Fb=G,a.sb=0,a.rb=0,a.Jb=0,a.uc=0,a.Rb=Id(a)&&!Jd(a),a.qc=g;if(a.qc||R){if(a.Oa===j||a.Oa===g&&a.Vc===g)a.qc=j;i=(Ac(a)?"&v=":"&r=")+Bc(a)}a.Jb+=a.sb;a.sb=0;a.uc+=a.rb;a.rb=0;Ad(a);var U=G="",ha="",ca="",L="",E="",ja="",ka="";if(!a.Oa===g||a.oc===g)G="&_vi="+Hc(a),U="&_vp="+encodeURIComponent(o),ha="&_vh="+Pa(Hd(a)),ca="&_vdd="+encodeURIComponent(b[C]),a.oc===g?(L=b.u,E=b.t,ja=jb(b.v),ka=jb(b.r)):(L=uc("u"),E=uc("t"),ja=jb(uc("v")),ka=jb(uc("r")));
o="";o=La(ja)?"&_pv="+ja:La(ka)?"&_pr="+ka:"&_pr=NA";ja="&_pu=";ka="&_pt=";ja+=L?L:"NA";ka+=E?E:"NA";L=!b.noCookies&&a.B.isSupported();E=c.getStrategyName?c.getStrategyName():"";return Qa()+"//"+b.pingServer+"/ping?h="+f+"&g="+d+"&p="+Pa(yd(a))+"&i="+Pa(Dd(a))+n+D+"&u="+a.Sa+"&t="+a.Ea+"&x=0&y=0&V=147"+Z("VS",E)+(L?"&n="+a.ac:"&nc=1")+l+i+R+Z("_vd",c.getTotalDuration())+G+U+ha+ja+ka+o+ca}q.Pb=function(){if(Id(this)&&!Jd(this))this.Rb=g;var a=zd(this);if(this.mc!=a)this.mc=a,Ad(this),this.qa()};
function Ad(a){var b=a.Ma;a.Ma=Id(a)?a.Jb<60?5E3:15E3:ud;b!=a.Ma&&Bd(a,a.Ma)}function Bd(a,b){clearInterval(a.vb);a.Ma=b;a.vb=setInterval(v(a.qa,a),b)}function zd(a){return a.ha.getState()+a.ha.getContentType()}function Id(a){return a.ha.getState()==="s2"||Jd(a)}function Jd(a){return a.ha.getContentType()==="ad"}q.wd=function(){Id(this)===g&&(this.sb+=1,this.ha.getContentType()===M&&(this.rb+=1))};q.te=function(){window.parent.postMessage("cbdata?","*")};
q.Kd=function(a){if(a.source===window.parent&&(a=a.data,La(a)&&a.indexOf("domain=")===0)){this.oc=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;t(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});Ja(window,"message",this.Ab);clearInterval(this.qb);this.qb=e;this.Vc=g;this.qa()}};q.setProperty=function(a,b){var c=j,d=this;t(wd,function(f){if(a.toLowerCase()==f)return d.ta[f]=b,c=g,j});return c};
q.terminate=function(){clearInterval(this.Hc);clearInterval(this.qb);clearInterval(this.Ga);Ja(window,"message",this.Ab);td.la.terminate.call(this)};q.za=function(){td.la.za.call(this);this.fd=this.a=this.Ab=h};function $(a){this.a=a;this.D=g;this.F=j;this.q=u();this.Ga=this.xa=this.Da=e;this.fa()}q=$.prototype;q.fa=function(){this.Ga=setInterval(s(this.Pb,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.ea()};q.Pb=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ga),this.Ga=e,this.ea()};q.ea=function(){if(!this.F)this.F=g};function Kd(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}q.J=m("D");
q.M=function(){var a="";Ma(this.a.getVideoData)&&(a=(a=this.a.getVideoData())&&a.title||"");return a};q.H=function(){return Kd(this)||this.a.getVideoUrl()};q.T=function(){return M};q.O=p("");q.aa=function(){var a=this.a.getDuration();return Ka(a)?a*1E3:a};q.G=function(){if(!this.F)return N;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};q.U=function(){var a=this.a.getCurrentTime();return y(a)};q.S=p(-1);q.$=function(){return"http://img.youtube.com/vi/"+Kd(this)+"/default.jpg"};
q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:Ya(this.q)};q.Y=m("Da");q.P=m("xa");q.Z=p("YT");$.prototype.getStrategyName=$.prototype.Z;$.prototype.isReady=$.prototype.J;$.prototype.getTitle=$.prototype.M;$.prototype.getVideoPath=$.prototype.H;$.prototype.getContentType=$.prototype.T;$.prototype.getAdPosition=$.prototype.O;$.prototype.getTotalDuration=$.prototype.aa;$.prototype.getState=$.prototype.G;$.prototype.getCurrentPlayTime=$.prototype.U;$.prototype.getBitrate=$.prototype.S;
$.prototype.getThumbnailPath=$.prototype.$;$.prototype.getPlayerType=$.prototype.X;$.prototype.getAutoplayType=$.prototype.Q;$.prototype.getViewStartTime=$.prototype.ba;$.prototype.getSections=$.prototype.Y;$.prototype.getAuthors=$.prototype.P;$.verify=function(a){return Ma(a.getDuration)&&Ma(a.getVideoUrl)&&Ma(a.getVideoEmbedCode)};function Vd(){r._cbv_strategies||(r._cbv_strategies=[]);r._cbv_strategies.push(X);r._cbv_strategies.push(S);r._cbv_strategies.push(Q);r._cbv_strategies.push($);r._cbv_strategies.push(T);r._cbv_strategies.push(P);r._cbv_strategies.push(O);r._cbv_strategies.push(V);r._cbv_strategies.push(W);r._cbv_strategies.push(Y);this.vc=[];this.ta=[];this.k=r._sf_async_config||{};bc("_cbv",v(this.Ld,this));if(this.k[vd]!==j)this.Dd=hb(v(this.Kc,this),5E3),this.Kc(),setTimeout(v(this.wa,this),3E4)}
Vd.prototype.Ld=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){Wd();return}else if(b==="removePlayer"){Xd(this,a[1]);return}else if(b==="setProps"){Yd(a[1])||this.ta.push(a[1]);return}}Zd(this,a)};function $d(){if(Ma(window.videojs)&&Ma(window.videojs.plugin))try{return window.videojs.plugin("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)}),g}catch(a){}return j}
function Zd(a,b){var c=j,d=r._cbv_strategies;w(window.jwplayer)&&(b=Ma(b)?b():b);t(d,function(a){if(a.verify(b))return c=a,j});c&&ae(a,b,c)}function Xd(a,b){var c=a.vc,d=r.pSUPERFLY_video,f=Ua(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=Ua(d,function(a){return a.a===b});f!==-1&&d.splice(f,1)[0].za()}function Yd(a){if(!w(a))return j;var b=a.player,c=Wa(function(a){return a.a===b});return!w(c)?j:be(c,a)}
function be(a,b){var c=j;t(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}function ae(a,b,c){var d=j;t(a.vc,function(a){if(b===a)return d=g,j});if(!d){c=new td(b,c);r.pSUPERFLY_video.push(c);for(var f=a.ta.length-1;f>-1;f--)be(c,a.ta[f])&&a.ta.splice(f,1);c.ob();a.vc.push(b)}}
Vd.prototype.Kc=function(){if(Ma(window.jwplayer)&&w(window.jwplayer())){this.wa();for(var a=0,b=window.jwplayer(a);w(b.id);)window._cbv.push(b),b=window.jwplayer(++a)}else{if(window.flowplayer&&(a=window.flowplayer())){this.wa();window._cbv.push(a);return}window.brightcove&&window.experienceJSON?(this.wa(),window._cbv.push(window.brightcove)):$d()?this.wa():window.kWidget?(this.wa(),window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))})):window.$pdk?(this.wa(),
window._cbv.push(window.$pdk)):window.KalturaPlayer&&Ma(window.KalturaPlayer.getPlayers)?(this.wa(),a=window.KalturaPlayer.getPlayers(),t(a,function(a){window._cbv.push(a)})):t(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})}};Vd.prototype.wa=function(){eb(this.Dd)};
function Wd(){function a(){function a(b){r._cbv.push(b.target)}var b=r.YT.Player;t(document.getElementsByTagName("iframe"),function(f){var i=f.src,l=i&&i.indexOf("www.youtube.com/embed/");i&&l>=0&&l<9&&new b(f,{events:{onReady:a}})})}if(r.YT&&r.YT.Player)a();else{var b=r.onYouTubeIframeAPIReady;r.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(r,arguments)}catch(c){}a()}}}};function ce(a){var b=de;return function(c,d){if(!Pb){b();var f=r._sf_async_config,i="",l=f[B],l=ua(l);/^\//.test(l)&&(i=x(r.location.hostname));f[ac]=Qa()+"//"+i+l;if(La(c))f[B]=J(c),d&&(f[$b]=d);else if(Ra(c)){var o=["authors","sections",$b,B,ac];t(c,function(a,b){if(Ua(o,function(a){return a===b})!==-1||b.indexOf("_")===0)f[b]=b===B?J(a):a})}a()}}};if(!H.N("cb_optout")){if(window.location==window.parent.location&&!r.pSUPERFLY){var ee=new jd,fe={};r.pSUPERFLY=fe;var ge=!!Zc,de=function(){ee.tb();ge&&Zc.evps()};fe.virtualPage=ce(function(){ee.Gb();ge&&Zc.svps()});fe.endTracking=de;fe.activity=v(ee.nd,ee);ee.ob();ed.exec(document.referrer)&&gd();var he=I.ga(g);if(!he?0:he.getItem("_cb_ip")){var ie=r.location;(!/^(.+[.])?chartbeat\.com$/.test(ie.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(ie.pathname))||Gb(fd)}else Ia(r,"message",hd)}r.pSUPERFLY_video||
(r.pSUPERFLY_video=[]);new Vd};})();
